=== 2016 November 29

This day is over too.
Today we talked about with the other Miskolc mentors that we’ve been feeling a bit down since the last few days.
Few students left, some of who stayed aren’t exactly at the top of their games.
The whole day was a bit gloomy and overshadowed by this.

During the day I didn’t manage to bring awareness to my talking, the way I talk.
In a few instances I was able to keep calm.
I think I was forcing myself to "`be fluent`".
Or, this is what I ended up doing.
What I wanted to do was to be able to repeat a "`blocked word`" better.
A few times it worked.

At the end of work I had a talk with my superiors/management.
I think that talk went well.
I stuttered a few times.
I stopped and backtracked and said what I wanted in a calmer fashion.
There’s still room for improvement!

Just before I’m writing this I talked with my girlfriend over the phone.
To say goodbye I wanted to say something to her, a word, which I’m always saying to her when we hang up.
The word is "`puszikállak`", which means something like "`lots of kisses`" in a cute way.
Anyway.
I wanted to say the word.
Just the word.
No frills before it.
I tried like ... whole bunch of times, but it took a while to say it.
5 minutes maybe?
I would have been able to say if I said something before it I think.
I’ve tried "`forming`" the word without trying to voice it.
Didn’t work.
I took deep breaths.
Tried "`hmming`" before the word.
To no avail.
Then I’ve managed to stutter the word and then I was able to say it without a problem .
I got a bit flustered.
But I think I still managed to keep being "`aware`" of the situation.
What did I notice? Even when I thought I was calm and relaxed I had a higher heart rate than normal I think.
The other thing is that I guess if I keep thinking about "`you have to be calm`" I never be calm.
Interesting that’s for sure, but the true emotion I feel is frustration.

Tomorrow, I want to be aware of my speech’s speed.
I want to talk slower.
I think I forgot today this.
Simply, I want to talk slower.
Not always.
I want to control the speed of my speech.
