=== 2016 November 30

I just finished my Skype session with Sarah.
How do I feel afterwards.
Still motivated, but I feel sometimes that as I learn more about my "`situation`" and thoughts it gets a bit complicated ... eh, scratch that thought!
Whatever happened so far and will happen from now on I feel I’m going forward and I’m getting to know myself better and better which is cool!

So, I’d like to kindly remind myself here that even if I block on a word there are several ways to experiment with to get that word into the conversation somehow.
Also, I want to remember how it feels to be in "`session mode`", where I’m open to experimentation, so that next time when I find myself in a speaking situation I could remember "`alternative`" ways to approach to say words, or to feel after a block or before a block.
Including trying how it feels to allow myself to talk slower.

Just another thought before closing this diary entry: *I remembered* just now why I wanted to work in Codecool in the first place -- *my original goal*.
It was something like *"`to get better at communication`"*.
And since that is my goal I want to take every opportunity to progress toward it.
