=== 2016 November 28

I’ve decided this minute that it would be a good idea to write some sort of diary or log about my thoughts on stammering and on my progress on dealing with it.

Today I had to talk a lot.
With my fellow mentors and with my students also.
Several times I wasn’t able to say what I wanted.
I got stuck on the word "`parameter`" (in Hungarian the first letter is emphasized more clearly so it’s even harder to pronounce).
This is just on "`those`" words I had trouble with today.
I’ve tried to relax, stop, before retrying the word only or retrying the word before or even a complete phrase.
Most of the time I wasn’t able to fully relax ... or let me rephrase, I didn’t feel "`effortlessness`", when I retried I was still making too much effort it seems.

I also hesitated a lot, before addressing one of the students, because his name is Krisztián (Christian basically).
I was trying to get calm, before saying it ... but it didn’t really work.
Eventually I just waited for a moment where I could address him without saying his name, because I "`wanted to get my message across`" -- it was important.

In the end of the day I had a one-on-one session with one of my students.
Several times I stuttered, blocked, restarted the word, but most of the time it didn’t work.
However, for a fraction of a moment, if I remember correctly and I hope I do!, I was able to sense, to bring myself into "`effortless`" mode when I tried to say a word the second time.
I was able to say the word slowly.
One or two times maybe.

Okay.
Enough of the negativity!
This was a crappy day, but I didn’t dodge hard words and replaced them all day long, which is a good thing.
I was able to arrange most of the things I wanted.

Tomorrow I want to focus on talking a bit _slooowly_ when I restart a word.
I want to bring awareness to this! Positivity!
