=== 2017 January 21

Yesterday was the leaving party for one of my fellow mentor.
He leaves the Miskolc team and joins the Budapest team -- so he remains our colleague only at a different location.

We had a few drinks and talked a lot about work and unrelated stuff also, a few interesting thing happened that I'd like to remember.

So, first of all I had a talk with our new back office assistant, her name is Anett.
She wanted to ask me about my stutter, because she told me she considered herself to be a stutterer earlier in her life.
I tried to tell her about the whole situation, about the "`stutterer mindset`" in a nutshell.
Anett pointed out that she noticed that I have trouble with particular sounds.
She also said that when she stuttered back in the days she _scanned_ for alternative ways for saying things.
I told her that _scanning_ is one of those habits that I want to lose and that it's ultimately unhelpful.
I liked talking about this, others joined the conversation too.

After the night what I feel is that I don't want to become someone who forcefully pushes down a topic down on others' throats in a situation like this.
Yesterday this didn't happen, the conversation about stuttering was organic.
What I mean by all of this is that even though I like to talk about this, I like being open about it, but I don't want to become someone who can ultimately talk _only_ about this.
So that's that, I don't want to push this onto others, but if they're interested I'm game to talk about it.

The other thing that happened is that after a few drinks (few in this instance means too much) I felt like I want to leave, go home.
Then the usual thing happened: the others who weren't so ready to leave just yet tried to make me stay.
I usually feel bad about leaving in these situations.
This isn't what bugs me though.
What bugs me is the fact that I try explain to the others why I want to leave and in the end somehow I end up feeling bad about.
I don't have to reason for why I'm leaving and I want to learn this.

While I was waking up, around 5am several things hurled inside my head.
It was quite overwhelming, but I had a bit of a hangover so I couldn't control it.
I was thinking about being inferior to others at work.
About what Attila -- the mentor who's going to Budapest -- told me.
About Máté -- the boss basically -- saying something "`I believe in that guy`" while pointing at me.
And of course about having a hangover, again, even though I promised myself that "`I won't drink anymore`".

Anyway, one interesting thing was conjured in my mind during that time was this.
I remember that I felt that *"`I want to think before saying something`"*, or "`doing`" for that matter.
I'd like if I could talk with others, the students, other mentors, anyone in a way where I don't "`babble`" around aimlessly.
I feel *I could be "`concise`" in what I want to say if I could think before I'm saying something*.

I remember however that after thinking about this I told myself that "hey, earlier I wanted to talk without thinking too much".

Quite opposing ideas, feelings.
I want to talk without thinking too much (without the hidden agenda), but I want to consider what I'm going to say before saying it.

One other thing is that I feel I'm taking too much time writing these.
I'll try and make these entries more straightforward if I can.
