=== 2017 January 3

A new year.
I don’t have too much time today, but here are *some good things already happened to me*, because I’ve stuck to it!

*I had fears*, pre-block moments weeks *before the first week in the new year*, because I knew I’ll be the one to facilitate the school, give tasks to the students.

*My fear was that something will go wrong* and it’ll be a disaster and _yadayada_.

What happened?
Prior to the start of the week I had these fears.
I’ve *remained objective* about my goals, myself, my scumbag mind.
After the first Monday I’ve *looked back on the events* and here's the summary.

Things deviated from my initial plan, but it wasn’t a disaster.
Some of the students gave *good feedback about me* ("`positive gossip`"").
And I’ve managed to *teach a new concept to them* about programming about which they clearly didn’t know jack.

Well.
Don’t have more time today.
One last thing.
One of the reasons of me coming to Codecool was that my *former job sometimes was tediously boring*.
It’s *only Tuesday* in the new year and ... _phew_ man *a lot has happened* already.
Awesome!
