=== 2017 January 18

I'm writing this after my first therapy session in 2017 with Sarah.
This entry is written primarily to test if I can format my diary in a such a way that it makes easier to read and to search.
We'll see!
Oh, I'll come up with a fancy way to flag important stuff in here too.

A few hours after the session and after the whole day I feel the following are the key "`takeaways`" today.

So, in order to become a _better version_ of myself I'd like to do the following.

* Continue develop good habits.
* Try not to appeal to everyone rigidly.
* Not to be hard on myself. Allow myself to be human.

Today was the day also where we've played with the class the _3 good/3 bad qualities_ game.
I've written the following about myself.

Good::
* Perfectionism.
* I want to be curious.
* I like to learn about almost anything (even useless things).

Bad::
* Perfectionism.
* *Setting the bar high* for others and *for myself*.

I wrote a third bad attribute about myself, but I don't remember what anymore.
Anyway, the main thing here is the one I've emphasized.
I set the bar too high sometimes, with which I'm pretty much setting myself up for failure.
However, I do like my perfectionist side, which kind of relates to this.
Bottom-line is that I want to aim for the balance, the perfect mix of these.

That's all for now. I have to find the middle ground between pushing to the limit and sleeping too. Days are short!

And to stop with something positive: after all this entry wasn't created only to justify trying out this new format.
