=== 2017 January 4

I’ve remembered a thought that had appeared in the US TV show called _Westworld_. A character played by Anthony Hopkins says the following.

____
The human intellect was like peacock feathers. It's an extravagant display intended to attract a mate. *All of art*, literature, a bit of Mozart, William Shakespeare, Michaelangelo, and the Empire State building... just *an elaborate mating ritual*. Maybe it doesn't matter that we have accomplished so much for the basest of reasons. The peacock can barely fly. It lives in the dirt, pecking insects out of the muck, consoling itself with its great beauty.
____

I thought this to be very captivating for some reason and I’ve remembered (the main idea) even after several days.

Stuttering-wise I had some conscious moments since last week where I purposefully *tried to _b-b-bounce_ or __sss__lide on non-feared words*.
Only in a few instances, I tried not to overdo it.

What did I notice?
Well, right now I feel that I was already tense *when I tried to experiment with this, as in I already blocked on a word* or similar before trying to bounce a non-feared word, so the sensation was kind of the same.
However I was able to bounce when I wanted to.
And it’s getting easier to do it.

I have to mention that *today I had to manage the class*, some 21 people, alone (well, for the most part I was alone).
Did I stutter?
Sure thing.
Did it bother me as much as it would have done a year ago for instances?
Not nearly.
Did it bother me in a few cases?
Yeah it did, but *I always said what I wanted*.

I also noticed that for few minutes (multiple times this day) I’ve experienced that *I’ve been "`in the zone`"* -- I was totally absorbed in what I was doing while explaining things to the class.
When I noticed that "`oh, I might have been in the zone`" I immediately noticed the "`__stuttery__ feelings`" I usually have (the scumbag mind) and I stuttered.
*I might have stuttered even when I was focused* on what I was doing, but *it didn’t matter* that time.

*I was braver today* than usual in a sense because *I’ve approached everything I did today with a "`I want to do this`" mindset*, or "`I’m gonna try this thing even if somebody will say afterwards that it was a crappy thing to do`".

It worked for the most part.
I’ve *had an idea* for an "`energizing routine`" to kick-off the day while walking to work and I *executed the idea right away, ASAP, before I could "`talk myself out of it`"*.
It worked brilliantly!

Okay.
Enough for now.
It was a good and productive day and it’s only Wednesday.
This place is crazy!
