=== 2017 January 23

In the last few days I've been out of touch with my stuttering.
I'm not sure if that's a good or a bad sign just now.
I've stuttered, no doubt about that, but it didn't leave too much of an impact on me.

Why did that happen?
Either I'm too busy with other stuff to dwell on it or I just don't care about it that much nowadays.

Both of these reasons are okay if I think about it ... so I -- and I almost wrote _shouldn't think about it then_ -- may want to consciously invite this thought a bit, for further inspection.

And upon further inspection, if I look back like two months ago, or even to my departure from London, what happened?

I wanted to make a summarized list of everything, but I've realized there are three things to point out.

1. I'm *not holding back as much* as before.
2. I *want to change* way *too much* sometimes.
3. I *lost my daily focus* on stuttering.

The _first_ one is *great*.

The _second_ one is still isn't half-bad, but I'd like to take the chance here to remind myself yet again that *it's okay*.

The _third_ one seems bit alarming, but if I think about it it was to be expected. Eventually something like that is bound to happen. Again, that is okay I think, nowadays there were a *lot of other stuff I've focused on*. The old flame will come back eventually -- if not, well then maybe that's a good sign!
