=== 2017 January 31

Today was the second mentor training day.

The main takeaways for me today were that

* *I usually take on others' responsibilities*,
* during meetings I want focus on *problems _and_ solutions*,
* and *specific feedback on behavior is best*.

Out of all these stuttering- and mindset-wise the first is the most interesting.

Why?
I do that even though *I'm aware of it*.
Why?
Somehow I, or *my mind, always manage to persuade me* ...

And right now a revelation came to me, *a feeling which I won't ignore* like so many others.
_Whys_ aren't important just now.
*What's important right is that I'm aware of this and that's enough*.

Something other to note.
I still notice that *I tense up inadvertently* in everyday situations.
Like during typing this, or when I was sitting of the back of the car of my colleague back to the station at Budapest.

I like to feel relaxed.
We've talked about this during the training as well as an important factor in being a good "`active listener`".
So, I'll *continue nurturing the good of habit of being relaxed* whenever it make sense.
