=== 2017 January 24

Yesterday our company's official "`coach`" Dávid asked if I'm available and willing to attend a training session in Budapest today.
It was on a short notice, but I said yes.
I was _curious_ to see and experience what it's like, because I've heard multiple different opinions about it -- some mentors liked it, some not too much.

I had a talk about this with Attila and he said that I should just try and keep an open mind and see how it goes, *form my own opinions*.
That was a good advice and I did just that.

I *didn't have time to worry* about the situation -- e.g. to leave my comfort zone. I *wasn't afflicted* by this *like I used to be* -- practice makes perfect!

I've talked about my stutter openly with people, but I didn't forced it, it came naturally into conversation.

When the training started I've kind of set up a single goal in my mind: *leave with a single "`takeaway`"*.
So I've worked towards this.

The theme of the training was _non-doing_ and it was setup to help mentors give some idea about how to help or guide students, how to improve their soft-skills.

I've taken some notes and underlined some thoughts I've liked.
Here are the top three.

* *Don't take responsibilities* from others.
* Give *feedback on behavior* -- instead of "`labelling`".
* Active listening -- *relaxing* while listening.

I've been also shown a technique that Sarah has used on me when we started our sessions.
The "`imagining your self on a scale`" thing.
I've called _Black Magic Coaching Scale_.
It was interesting to be on "`the other end`" of the technique.

I feel that it was helpful in both personal and professional sense.
I'll try to use what I've been shown or thought to the best of knowledge.

Finally I'd like to point out one key thing for myself.
*It's okay _not to_ experiment with what I've learnt _right frickin' now!_*
