=== 2017 January 27

Yesterday my girlfriend asked if I could go with her to a "`music venue`".
She's into musicals, operas and the like so I was skeptical obviously.
She really wanted to go and hadn't found anyone else who would be interested.

I said "`okay`".
*I wanted to keep open-mind*.

I've remained a bit skeptical though and made "`funny remarks`" about the situation (at least they were funny by my standards).
*I don't like the part of myself that makes these remarks* all the time.
I do think that these are good and funny when placed at the right time and place.
So I'll *try and be more "`cool`" when something unnecessary* or uncalled for *wants to leave my system*.

About the performance: it was pretty good.
The theme was: famous songs from plays, operas, etc. spaced with funny intermezzos and anecdotes.

I don't really like musicals and such, but I could appreciate the music.
It was full "`classical setup`".
Violins, flutes, woodwinds, brass instruments, etc., even a French conductor with all the wacky hand movements.

Five performers performed during the night, three girls and two guys.
Opera, light opera, musical singers, actors and whatnot.
All of them were great really.
I prefer a male singing voice so I'd appreciated the guys singing more.

*What captured my attention* though wasn't the fact they could sing, but *their "`presence`"*.
The presence of the guys especially.
The way they walked, the manner they carried themselves, the way they sat, their motions, everything oozed *confidence*.

The best thing happened in the end.
I was kind of feeling the whole performance was already too long and wanted to go.
Then, the opera guy (Zsolt Homonnay) came busting onto the stage to the music of _U Can't Touch This_ by MC Hammer.
I'm serious that I haven't laughed like yesterday in a _looong_ time.
Such a contrast.
And the best is that this performance was awesome too.

Conclusion: *keeping an open-mind is awesome*!
