=== 2017 February 12

Yesterday evening and today morning I was thinking about my session with Sarah.
I told her I want to set aside an hour for myself, _just_ for myself, where I can be like I'm during our sessions.
Then I've read https://www.reddit.com/r/GetMotivated/comments/5thc8s/tool_how_to_actually_make_meditation_a_habit_in/[this post on Reddit].

I've *talked about grounding, relaxing* and all that stuff with Sarah, but somehow *it didn't take true roots in me*.

*After reading the post I felt that I'm ready for this*.
Not just because someone told me, but I truly saw the benefit of it.

Also, setting aside a few minutes, or an hour every week _for myself_ seems silly now.

Meditating daily sounds a better idea now.

One last thing to note is, that *after reading the post and thinking about meditation* I quickly tried to meditate for a few minutes.
It was interesting that afterwards *I got a bit gloomy*, Eszti (my girlfriend) and my mother made a remark about it too.

I wasn't gloomy at all as far as I know.
*I was more like more aware of my surroundings, the voices, the gestures.*
It was interesting, but I don't want to seem gloomy when I'm too aware.
Smile!
