=== 2017 February 22

I wanted to write something here since last week, but somehow it didn't work out.

Because of this I was *_beating myself up_ subconsciously* (a little).
Something like "`you're not putting enough effort into this`" went through in my head a few times.

Fortunately *the part of my that is more aware* than a few months before is at work too.
It's *saying things like "`yeah, well, it's okay*, you were busy with a lot other things as well`".
And that helps.

Let's recap what has happened since last week.

* I've postponed my session with Sarah because I was at Budapest on that Wednesday.
*Interviewing Codecooler's* at our office in the capital.
* Had a *wonderful evening* with my girlfriend.
An "`after-Valentine's Day dinner`", because I couldn't care less about Valentine's Day, but I do enjoy a lovely dinner!
* Started *learning in a _mindful_ way about electronics* (voltage, current, all that stuff).
* Started *meditating* a few minutes a day.
* *Office yoga*.

The interviews were interesting.
*I was praised* by one of my fellow mentor.
He taught the way I've handled the interview was really good.
Before he said this *I thought it wasn't that good, but I wasn't affected by these thoughts* as much as my "`older version`" was.
I've getting more and more battle hardened.

The dinner was awesome.

I want *learn about micro-controllers, but I don't have the basics*.
Basics like how voltage, current and resistance relate ... I've learned about this, but I've never used it.
Anyway, I've *found a book online*, a complete course around electronics and I've decided to start reading it.
A few minutes a day.
Being *_mindful_ while I'm reading*.

Meditating.
I think I've wrote about this, but I've read a Reddit post about _mindfulness_ and _meditation_.
So after that I've decided that I want to experiment with this.
Since I've written about it *I'm meditating daily*.
Not in a rigid "`I have to meditate so leave me alone`" way.
More in a "okay, *I have some time, let's meditate 3 minutes and see how it goes*".
This way it works better, feels more relaxed.

I should note here that *meditation*, where you focus on your breathing, letting your usual thoughts go *is _haaard_*, but refereshing at the same time.

One another thing I've started doing is "`office yoga`".
By this I mean I'm just doing some *exercises during my workday* whenever I have time.
And also, I'm breaking up my day in a "`Pomodoro way`" (I'm a poet and I didn't even know it!).
I'm not sticking to it strictly, because I don't like doing it that way.

I gave 25 minutes for myself to write something here by the way.
That's up, but I think what I've written here is enough for my purposes: _to keep being aware_.
