=== 2017 February 14

The last two days were difficult.
I felt overwhelmed multiple times, mostly because I wasn't able to let go of things.
I wanted to do _everything_ all at once impeccably.
Nobody can do that, so _no wonder_.

Anyway, I had a talk with one of the students today.
I wanted to "`help him`".
Forcibly, I admit, he never asked directly for help.
But, this matter is for another day.

The point is that while talking with him I've remembered a quote I've read in the "`stuttering self-help book`" a year before my sessions with Sarah.

I've managed to find out with some digging that it was a book by Cavett Robert from  his book _Human Engineering and Motivation_.
As a student he asked his professor to give a definition of "`character`".
His professor's reply went as follows.

____
Young fellow I'm not sure, but I am going to give you a definition that I want you to keep until you can find a better one. +
*Character is the ability to carry out a good resolution long after the mood in which it was made has left you.* +
Now I didn't say just the ability to carry out a good resolution. We all have our moments of supreme dedication -- whether it be fidelity to a person or loyalty to an ideal.
But how few of us carry out that resolution when the mood has left us and the tides of temptation come sweeping in. +
Tomorrow morning, you are going to have a test on the material we have covered over the past few days. +
Tonight you will perhaps decide that you are going to get up at six o'clock in the morning and study for this test. And actually you are going to get up in the morning -- that is, tonight you are, because you are in the mood. +
But tomorrow morning when you stick your foot out and it touches the cold floor you don't have that mood any longer. *I say character is that which you have within yourself to substitute for the mood which has left you. Character is that which causes you to exercise the self-discipline to get up anyway.*
____

During my talk with the student I decided, because I was _motivated_, that I'll search for this quote and I've stuck to it.

But now, well after 11pm, I'm feeling that *I wasn't able to set my priorities straight* today.

I feel *I'm someone who has the character to _remember_ the original mood* that has left him.
Now I *want to work on being someone who can also substitute it* better than I usually do.
