=== 2017 February 7

It's the third day and (for now) the end of the Mentor Training.

During my journey from the training location to the railway station I've *looked back* to the last week.
It *felt difficult to remember _everything_* since my last therapy session with Sarah.
A few things came to mind in regards to that.

* Without trying to dug hard *no __suuu__per negative thoughts came* to mind,
* except one: the fact that "no __suuu__per negative thoughts came to mind.
* But this I'm *attributing to me being the way I am* right now.

A good description to the _way I am right now_  would be what *Sarah told me* last time about working with me.
I don't remember the exact words, but I do *remember the gestures she used and the fluffy sensation* I was feeling when hearing the words. So I feel like being _that way_ still.

When I think about this I feel *what I do is enough*.

A few things are on the top of my head. In no particular order.

Remembering that *Sarah told me that she thinks I put in a lot of effort into are sessions* and the feeling I felt hearing that: it felt good, but I remember that *my mind was trying to _play_ me with stuff like "`oh of course she says that`"* and that I had to "`battle it out`" with saying stuff to myself "`it looks like hers is genuine response man`".

The other thing is the situational game we've played during the training.
Someone needed to *improvise in front of the others* (five other people) in a random topic.
*I volunteered.*
The topic was "`my cool imaginary friend`".
The others' task were to assess how I use *_words_* how I use my voice (*_music_*) and how I use space, my hands (*_dance_*).

I stood in front of everyone and talked about this non-existent guy picking up girls, ordering drinks at the bar in a "`cool way`" and trying to dangerously pass a car while I was driving by hijacking the steering wheel.

I had two minutes.
After it I felt a bit hot.
I stuttered once or maybe twice.

After it the others gave me a feedback about how it was.
I was still feeling a bit hot, because I *felt that it wasn't _that_ good*.
But, the *others said surprisingly good stuff* about how my voice were loud and soft sometimes (going through the spectrum) or that I tried to keep eye-contact with everyone for a little while.

The *feedback wasn't _completely_ positive*, I would say all were useful.
Someone pointed out that I tried to make my imaginary friend too realistic, they would've expected a world-traveler type of action here kind of guy.
Yeah, *I didn't like that, but I was like "`hey, I was first, others after me will have it easier`"*.

What *I want to point out* is that this time *I had a much easier time processing* the feedback and the whole day.
It was easier to see the good in everything.

Something else to note is that learning about these "`non-doing`" principles helps too.

To sum up I'd say that with *more and more practice* I'm becoming *more and more aware* and that's good.

Oh, two things came to just now.

I *was aware of _softening_* during this week.
*Still thinking about it as a way to be fluent*, a way to not show that I stutter I feel.
For example when saying _köszönöm_ today in multiple places (café, restaurant) I got stuck on the word.
I *wanted to soften it, but thinking about that didn't bring up memories about relaxing, focusing on the first syllable*, etc.

But, there were a *few cases when this happened* and it worked.
*I'm getting there!*

The other thing ... it kind of left me, but of yeah, it's back.
So the other cool thing is that *I've noticed today that I've recognized flaws in others* that I've already identified in myself.
Sarah will love this, but *they were saying stuff like "`I should have done that`" or that "`I shouldn't think that`"*.

I don't remember the exact thing they said.
Unfortunately in my mind I was focusing on "`trying to flag this up to them and to help`".
*I felt "`__haha__, I'm smarter than you and you don't even know it`"*.

Then I *remembered this "`non-doing`" thing* and that I've decided that *I want to develop the habit of "`not trying to help others forcefully`"*.
For multiple reasons.
If it's my idea or forced it won't stick.

If I would take the time to re-read what *I've written here in the last few weeks* I would find that wrote something that *"`I don't want to become someone who's forcing his stuttering baggage onto others`"* or something like that.

And now I think I can refine this with something I've learnt during the training: *_solution focus_ is more beneficial than _problem focus_*.

So, turning around what I've written earlier ...

Oh, I *was thinking "`this will be something new`"*, but I've realized I've *already came to this conclusion*.

Which is that *I want to be someone who _thinks_ before he _talks_*.

And now I'm getting teary-eyed a bit, because this is what exactly happened.
