=== 2017 February 1

Just a thought that came to me while I was in the middle of waking up.

Yesterday during the mentor training *I was praised for having shown symptoms of "`growth mindset`"*.
We were asked to solve a simple logical challenge, by ourselves in a few minutes.

After the game our coach, Dávid, pointed out that he wasn't interested in the outcome of the game, but our behavior.
He mentioned that a few of us started the challenge with a "`fixed mindset`", saying "`I'm not good at games like this`", or similar.

It was interesting to hear his *opinion about me*.
I wasn't aware that *I said* something like "`I have **no _frickin'_ clue how to solve this, but _I'll try to do something anyway_**`".

There was another point he mentioned, but I don't remember that.

*I remember saying that I didn't get frustrated by not being the first* one to figure out the solution.
Instead *what bugged me that I saw someone else's solution* which kind of spoiled my fun.
Because I like to get to a solution myself.
That's how I learn.

After the game we watched a video on YouTube about growth mindset.
Seeing it and hearing *the positive feedback* I mentioned before *reinforces me that I'm a path that's beneficial for me*.
