=== 2017 March 9

Yesterday I've attended a play with Eszter.
She asked me to accompany her a few days before.
At first I hesitated, *my usual "`negative`" self surfaced*.
I told Eszter that "`I'm not in a state in which I can make a decision, *ask me tomorrow*`".

So she asked me and I said "`of course, let's go`".
I thought about it and I envisioned myself enjoying it.
I've *experimented with the idea that it could be really good* or it could be interesting in a way I wouldn't even think about at first.

The play itself was a rendition of a well-known Hungarian play _The Tragedy of Man_.
Very famous.

Anyway, what happened was that I kind of enjoyed it.
It was too long and the ending was rushed and dense, but otherwise the night was enjoyable, I was able to enjoy it on different axes.

One thing worth mentioning here is that I *saw my high-school Hungarian literature teacher*.
She was (I assume) attending with her class -- I saw several high-school student in the audience.

I've played with the idea that I go up to her and initiate a conversation, but *I was afraid*.
Afraid, because maybe *she wouldn't recognize me* and then *I would need to introduce myself* and then that would be kind of hard.

Eventually I didn't go up to her, I convinced myself that "`this isn't the right time`".
I was thinking about why "`would I speak to her?`" and I ended up with the answer "`I don't want to speak with her really`".

Sometimes, when I'm in situations like this, it kind of feels I'm not sure if I really want to talk to somebody or that I just want to talk to them to prove to myself that I can talk with them.

And now, reflecting on what happened I'm not sure still if I wanted to talk to her or not.

So, in order that I could decide this with a hundred percent accuracy, next time something like this happens I'll try to *overcome fear with _curiosity_*.
