=== 2016 December 21

The last week was mostly about partying and playing with my goddaughter.

We had a staff lunch on Thursday evening, the school party on Friday evening and another school trip that was yesterday and today (Tuesday evening and Wednesday morning).

On Thursday I really *liked the lunch we had: amazing food and drinks*, only a few people present.
On Friday *I enjoyed the food we prepared* for the guests in the school.
Yesterday it *felt good to horse around with the students and other mentors*.

So generally it was okay.
The part I *didn’t like* is the fact that there are always certain people participating in these events *who always want to "`blackmail`" others to drink or enjoy the party* even more.

In similar situations I *usually feel bad for not being compatible with these people* mindsets'.
Earlier in my life this was worse I think, others were able to "`control`" me.
It got better with time and I started to take control and do what I really want even if I felt "`I made a bad choice and I suck`".

Nowadays, _today_, it’s almost the same, except *I’m aware that what I want is what really matters and I shouldn’t feel bad about that*.

I just remembered this about "`feeling not being compatible`".

So, when *someone asks me "`do you want to come to the party?`" my usual response is or was "`no`"* and I felt bad about.
If others *coerced me* into coming I felt bad about that.
If I said "`yes`" I usually *hated being there* and felt bad about that=. If I’m already in a party and try leave earlier I *feel bad for wanting to leave*.

I feel like this a lot, not just about going to parties (however I don’t have any other examples at hand).

Now, I feel that I can do something about this knowledge: *there are no best choice only the choice I come up with*.

In term of "`attending parties`" I think the best for me would be to attend and then *leave whenever I feel that being there is not beneficial for _me_* anymore.

During these events in the last week the "`recurring feelings`" were: feeling weird, being envious.

Weird?
I was the driver to the place where we held the party yesterday (about an hour drive from where the school is in a hilly, secluded village).
In the car there were times when nobody said anything.
I felt weird, because ... I’m not even sure why.
The same thing happened on the way home, however I had a headache so I wasn’t bothered by the silence too much.

Envious?
Yeah, I see awesome people everyday and I feel I’m not as good as them. That’s maybe true, and I know most of them may not as good as me in certain aspects of work or life, but still I feel like that.
It’s hard to _grok_ it.
The worst is when I see that they don’t give a crap about anything and still ... yeah, seeing them being carefree is hard.
I’m envious of their carefreeness.

Okay, but *enough of this negativity!*
Let’s get back to stuttering!

Stuttering-wise this last week was kind of stagnating.
Since my last session with Sarah, when we talked about pre-block, the only thing that changed is that now *I’m aware of the battle going on in my head* right before I’m entering into "`stutter struggle mode`".
I’m a long way from winning the battles!
