=== 2016 December 6

Monday and Tuesday is behind me.
This is What happened stuttering-wise.

On Monday we, the mentors, started the day *without a proper plan or schedule for day, and I was frustrated because of this*.
It’s *not my job to create one, but I still felt it was my responsibility*.

Anyway, I *tried to do my best* considering that we had zero time to plan anything.

My fellow mentor came up with a plan, which basically was to assign 4-5 people to a mentor and "`practice`" with them for the upcoming (this Wednesday and Thursday BFA - big final assignment, actually big _f*cking_ assignment).

So I sit with three students and talked with them.
What happened?
I think I *barely stopped talking for the day*.
Stuttered a lot, *haven’t avoided too much words* (and when I did I tried to introduce those words into the conversation again).
I was semi-aware of the fact that I was talking too fast sometimes and I was able to "`intervene`" and slow my speech a bit a few times.

However, I felt or did the following: I’ve noticed that I stuttered, I continued, but I *got more and more "`hyped`"* overtime.
And by the end of the day I was exhausted.
I felt my larynx and my entire body was tired.
I had a mild throat ache.

After the day was over *I examined what happened*.

* I didn’t take a short break and stood up the whole day (maybe once).
* My water intake was lower than normal.
* I had a mindset where *I noticed I stuttered, but I wanted to keep on talking* so that I can talk better next time.

Basically *I wasn’t able to let go of "`fluent speech`"*.

This was Monday.
Today we did the same thing, I sit with five or six students and tried to tell them the same stuff that I talked about on Monday.
What did I do differently?
I was more prepared.
I set a timer for 50 minutes and told everybody that "`okay guys, let’s do this for 50 minutes, after that I’ll need to take a breather and stand up to stretch a bit`".
So I did this.
What happened?
At the end of the day *I was less tired and I was able to concentrate more easily on what I wanted to say*.
I still stuttered and I have room for improvement.

On both days I talked about my stuttering with the students (some of them are older than me, so it’s funny to call them as such).
They were interested about "`why did I choose to work at Codecool in Hungary instead of earning more money in London as an engineer.

I told them *I came to Codecool to improve my communication skills*.
