=== 2016 December 5

*tl;dr* My Friday, Saturday and Sunday in a nutshell: Friday and Saturday was busy, Sunday I did nothing at all and I was miserable.

Last Friday I went to visit the Budapest office with my bosses, Máté and Józsi.
On the way to Budapest in the car we talked about work related things and problems.
Being with these guys in a car is a bit overwhelming.
They’re really down-to-the-earth guys, but still very overwhelming.
Always driven, very intelligent, well-spoken, funny, charismatic.
Typical leader material.

Anyway, I talked with Máté (when we were the only ones in the car) about "`stuttering`".
He initiated the conversation with a remark "`I see words with _P_ are problematic`" or something like that.
I went along with it for a while and tried to lay out the problem of "`the scumbag brain`" for him.
Talking about this didn’t make me more relaxed at the time.
Or at all, but now that I think about it ... it made me a bit more "`aware`".
It was easier to keep my concentration while talking: being a bit slower, not holding my breath, or noticing that I’m holding it.

We arrived at the Budapest school around just after 10am.
The students were presenting their weekly work, progress to IT-professionals from various Hungarian companies (they do this regularly, every week to "`get the hang of it`" and to keep them motivated).

The presentations themselves weren’t always that good, but the students and the other mentors’ approach, motivation was top notch, highly professional.
Overwhelming!

Then we *had lunch with* these *IT-professionals*.
Which, again, was overwhelming.
These guys were representing multinational IT companies.
Some of them were University educators also.
Still, *I tried to initiate* a few *conversations*.
I was thinking "`okay, *I want to say X`" so I said X*.
Not always, but *compared to my "`old self`" this was an improvement*.

After lunch there were some other presentations by these IT people during which *I wasn’t able to ask my questions*.
I had some, but *I held them in*.
For two reasons, *I wanted to give space for students to ask their own questions, and I got flustered about "`not being able to ask what I wanted`"*.

*I told myself* that "`okay, *I’ll wait and after that guy *I’ll ask my question`" and time went by and the presentation was over*.
That *left a bad taste in my mouth*, however we had the chance to talk with these guys after their presentations was over and *I managed to ask my questions* (almost all of them, we had to go, so there wasn’t time for everything).

On the way home in the car Máté was asking me how did I feel myself at the office, what did I notice.
I told him that I felt the whole atmosphere was professional compared to the atmosphere in the Miskolc school.

He also mentioned a game or method he learned from a "`mentor coach`" (motivational, life-style coaches hired by Codecool - two guys not from IT fields, more versed in philosophy and self-learning, etc.).
It’s called the "`positive gossip`" game.

A person from a group of 5-10 people sits apart from and with his back turned from the group while the group "`gossips`" about him, but only positive things.

This is supposed to help us to learn "`how to give positive feedback`", because it’s  kind of hard to do that for some people (me included).

The next stage of the game is "`giving direct positive feedback`" and the next after that is "`giving direct negative feedback`".
The rules for giving negative feedback is that it should be phrased in a "`matter of fact way`".

Like "`last week I felt I wasn’t able to progress with my work, because John was lagging behind with his work`", instead of "`John! You dumb nitwit, why didn’t you work faster, huh?! I had to do overtime because of you!`".

Anyway, I think this is a good idea, *I just don’t know* yet *how to "`execute`" this* in action with our students ... but *I want to do it*.
*I mention this, because I think, right now, I worry too much about this*.
