=== 2016 December 2

Yesterday I had some beers with a few colleagues.
Also we had a quite useful and intense meeting about a lot of stuff.
Just a few thoughts that occurred to me after it.

My boss said that he wants us, the mentors, to be more responsive.
*Don’t just sit idle and talk about solutions*, but rather *jump into them and see what comes out of them*.
He said something like *don’t wait for everyone to give your ideas a green flag*.
I think he’s right, but more importantly I think we should value a job like this and do our best to utilize it fully.

The other thing was that before the meeting and the drinks I felt different then usual.
Usually I’m getting worked up before these kind of situations.
I kept an open mindset.

Also, in the morning instead of sitting in front of my computer *I deliberately choose to stand up and walk around* the students to see what are they doing and I ended up helping a few of them.
While talking with them I experimented with "`stuttering fluently`".
I think I did rather well.
Also, I tried to extend my awareness, tried to shift myself out of "`heady`" mode.
It’s quite hard to do it, but it’s quite refreshing to do something like that.

Well, I’m off to work, I’m heading with my boss to Budapest to meet up with the Budapest mentors and to see how’s the Budapest office/school is like.
