=== 2016 December 14

Wow, the last week went by in a flash.
I somehow managed to skip on writing anything here unfortunately.
It’s really cold around here (-7 degrees :O) and it’s quite the struggle to get up in the morning (when I usually write these with a fresh mind).

Anyway, this is what’s happened stuttering wise: I completely managed to forget about the idea of "`grounding`".
The Thursday and Friday after our session on Wednesday was really busy, with the final exams for the students that the memory of it was phased out of my mind.

I did watch the video about "`Body Language`".
I already heard about the term "`fake it ‘til you make it`" from Elliot, but this video gave a lot more context to it (testosterone and cortisol levels changing due to our mindset).

On Friday the students received their exam results personally and I was the one who talked with almost all of them (10 or so people).
What *I’ve noticed that I still rushing*, getting fired up while talking.
I’m not sure why, maybe subconsciously I want to be the one doing the talking to show my conversational partner that I’m the man or similar.

Anyway, *I really want to experiment with letting this feeling go and focusing my mind on what I want to say*.
Actually this is what "`grounding`" was about I guess :)

For a few times this week *I consciously tried to stretch out the syllables of the words* I blocked on while talking among relatives.
When I really got into *the mindset which focuses on "`stretching out the next syllable`" it worked*, however this is still hard to do because of the "`hidden agenda`" of the mind.

If I look back on the last week *I was consciously doing what I wanted*, *not avoiding to say or do what I wanted and that’s awesome*, because usually what happened after a situation where I avoided doing what was in my head was that I felt bad about it.
This didn’t happen this time around.

I remember that when I started the therapy I told myself (I might have told this Sarah as well at one point) that I *"`don’t want to hold back on saying what’s on my mind`"* (or doing it for that matter).

I think I’ve *improved a lot in regards* to this.
