=== 2016 December 25

Yesterday was *busy as hell*.
The immediate family is together at our place:  my mother and grandmother, my brother and his wife and their daughter, my goddaughter.

Unfortunately my mother got sick the day before and my sister-in-law too.
She has a cyst in her leg and is pretty much unable to walk without elbow-crutches (it’s not as bad as it sounds, she’ll be okay, but her leg is inflamed right now).
Anyway, me and my brother were managing the household yesterday: shopping, baking, dishwashing, bathing my goddaughter, cleaning up, dressing up the Christmas tree, cleaning up and I don’t know what else.

What’s interesting in this is that I was being mad about my sister-in-law, because sometimes (actually it feels like all the time) she can act like a harpy towards my brother and sometimes towards me as well.

Anyway, I was *having this feeling "`being mad at someone`"*, but I also was *able to zoom out on it* and "`chew`" on it a bit, before drawing a conclusion on the thought.

I also was conscious sometimes that "`I *wanted to lecture*`" her about something the way I usually do (to satisfy my need to say something and maybe to have the last word and "`win`" an argument), but instead of doing it I *chose to just "`observe`"*.

What’s *even more interesting* is the fact that I slept quite bad yesterday (I was dead tired, but I wasn’t able to sleep, because my sugar intake for the day was through the roof) and I *had a dream about the first week of school next year*.

Last Friday I’ve prepared a rough schedule for the week, a daily routine for each day of the first week.
What I *was dreaming* about was that it’s already Tuesday and *somehow I "`wasted`" the whole Monday without executing my previous plan*.

Tuesday *my fear was that "`now, at this point, I cannot follow up the plan I made and it’s all in vain and I’ve failed`"*, I felt paralyzed. After waking up I realized that my fear is based around my "`all or nothing`" behavior, the need to be perfect.

I think I *was half-asleep* when my consciousness kicked in somehow and *managed to remember that "`hey man, it’s still 2016, chill out`"*.
Or maybe it was only after I was fully awake.
It’s *frightening how big of a scumbag the brain really is*.

Conclusion: yeah, I’m a bit *concerned about the first week of 2017*, but based on past experience *it’ll be alright* even if my brain wants to convince me otherwise.
Even if I’m going to waste that entire Monday somehow on Tuesday I’ll probably still be able to salvage my plan or a part of it and that’s okay.

Happy Christmas!
